apiVersion: v1
kind: Service
metadata:
  name: main-service-lb
  namespace: main-service-ns
spec:
  selector:
    app: main-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer